---
timezone: UTC
title: Paul Hershey
email: hersheypaul@gmail.com
description: 'Write your description here for you website SEO.

'
url:
twitter:
  username: paulhershey
  card: summary
social:
  links:
    - https://twitter.com/paulhershey
baseurl: 'lazerTiger'
collections:
  pages:
    output: true
    permalink: "/:path/"
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page
    title: ''
    description: ''
    image:
      name: ''
      path: ''
      width: ''
      height: ''
plugins:
- jekyll-sitemap
- jekyll-seo-tag
permalink: "/articles/:title/"
highlighter: rouge
markdown: kramdown
